### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by XRui-Y** [chuchen2017/TrajGDM#1]
Hi, thanks for publicizing the research code, but I didn't find "from utils.data_loader import load_trajs" in the runtime, can you share the code about the utils file, thanks!

**Comment by chuchen2017** [comment]
Thanks for rising this issue! We are sorry for our mistake. The file data_loader has been uploaded now. Thanks for your interest.

**Comment by XRui-Y** [comment]
> 感谢您提出这个问题！我们对我们的错误感到抱歉。文件 data_loader 现已上传。感谢您的关注。

Thank you for uploading, I have another question to ask, how do you save the generated trajectory in the code, and how is figure 5 plotted?I would appreciate your guidance. Thank you.

**Comment by chuchen2017** [comment]
Saving: You could modify the code and save the trajs_generated as generated trajectories. 
Figure: To plot Figure 5, you need to save the probability distribution and the generated trajectories output by the trajectory decoder in each step of the DDPM generation process. A few personalized modifications are required, but it should not be a hard one.

**Comment by XRui-Y** [comment]
> 保存：您可以修改代码并将trajs_generate保存为生成的轨迹。 图：要绘制图 5，需要保存 DDPM 生成过程的每一步中轨迹解码器输出的概率分布和生成的轨迹。需要进行一些个性化修改，但这应该不是一件困难的事情。

Thanks for your help, I think I should be able to pull it off!
